### PR TITLE
landing page per tag, improve index

### LINKED ISSUE #661: Add tags
@graemerocher 

 > The PM of Kotlin pointed out that this link is broken https://guides.micronaut.io/tags/kotlin.html
> apparently it was linked from https://kotlinlang.org/docs/server-overview.html#deploying-kotlin-server-side-applications and used to work

### PR DESCRIPTION
**Pull request by sdelamo**
Close https://github.com/micronaut-projects/micronaut-guides/issues/661

### CODE REVIEW

File: buildSrc/src/main/groovy/io/micronaut/guides/IndexGenerator.groovy [hunk 1]
```diff
@@ -31,52 +36,99 @@ class IndexGenerator {
...
+            index += '    </div>'
+            index += '  </div>'
+            index += '</div>'
+            index += '</div>'
+            index += '<div class="categorygrid">'
+            index += '<div class="row">'
+            index += '    <div class="inner" style="padding: 0">'
+            index += TagCloud.tagCloud(tags)
+            index += '    </div>'
+            index += '</div>'
```
Comment (timyates) [inline buildSrc/src/main/groovy/io/micronaut/guides/IndexGenerator.groovy]: Think we need a new class on this, Row has

```
margin-right: -15px;
margin-left: -15px;
```

Which causes the tags to go outside of the DIV border

image

**Review by timyates — APPROVED** [review]
